name: Snyk Security Scan
on:
  push:
    branches:
      - main # Change to your main branch name

jobs:
  synk:
    permissions:
      contents: read
      packages: write
      security-events: write
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change to your preferred Node.js version

      - name: Install project dependencies
        run: npm install

      - name: Run Snyk Security Scan
        uses: snyk/actions/node@master # Use the Snyk GitHub Actions action
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
